import { StyleSheet } from 'react-native';
import { Colors } from '@/theme/colors';
import { FontFamily, FontSize } from '@/theme/typography';
import { Radius, Spacing } from '@/theme/spacing';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: Colors.bg.base,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.xl,
    paddingVertical: Spacing.md,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  liveDot: {
    width: 11,
    height: 11,
    borderRadius: 6,
    backgroundColor: Colors.accent.green,
    shadowColor: Colors.accent.green,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.9,
    shadowRadius: 6,
    elevation: 4,
  },
  logoText: {
    fontFamily: FontFamily.displayBold,
    fontSize: 23,
    color: Colors.text.primary,
    letterSpacing: 1.5,
  },
  settingsBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#1a1d20',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  settingsIcon: {
    fontSize: 18,
    color: Colors.text.secondary,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: Spacing.xl,
    paddingBottom: Spacing['3xl'],
    gap: Spacing.lg,
  },
  chipsScroll: {
    marginHorizontal: -Spacing.xl,
  },
  chipsContainer: {
    paddingHorizontal: Spacing.xl,
    gap: Spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
  },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm - 2,
    borderRadius: Radius.full,
    backgroundColor: Colors.bg.surface,
    borderWidth: 1,
    borderColor: Colors.border.default,
  },
  chipActive: {
    backgroundColor: Colors.accent.greenSubtle,
    borderColor: Colors.accent.greenBorder,
  },
  chipText: {
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.sm,
    color: Colors.text.muted,
  },
  chipTextActive: {
    color: Colors.accent.green,
  },
  soonBadge: {
    backgroundColor: Colors.bg.elevated,
    borderRadius: Radius.xs,
    paddingHorizontal: 4,
    paddingVertical: 1,
  },
  soonText: {
    fontFamily: FontFamily.bodyBold,
    fontSize: 8,
    color: Colors.text.ghost,
    letterSpacing: 0.5,
  },
  tournamentCard: {
    backgroundColor: Colors.bg.surface,
    borderRadius: Radius.xl,
    borderWidth: 1,
    borderColor: Colors.accent.greenBorder,
    padding: Spacing.xl,
    gap: Spacing.sm,
  },
  tournamentCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  tournamentCardHeaderLeft: {
    flex: 1,
    gap: Spacing.xs,
  },
  livePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    backgroundColor: Colors.accent.greenSubtle,
    borderRadius: Radius.full,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 3,
    alignSelf: 'flex-start',
  },
  livePillDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: Colors.accent.green,
  },
  livePillText: {
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.xs,
    color: Colors.accent.green,
    letterSpacing: 0.8,
  },
  tournamentRoundText: {
    fontFamily: FontFamily.body,
    fontSize: FontSize.sm,
    color: Colors.text.muted,
    marginTop: 2,
  },
  playButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: Colors.accent.green,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: Spacing.md,
  },
  playButtonIcon: {
    fontFamily: FontFamily.bodyBold,
    fontSize: 13,
    color: Colors.accent.greenDark,
    marginLeft: 2,
  },
  tournamentName: {
    fontFamily: FontFamily.displayBold,
    fontSize: FontSize['2xl'],
    color: Colors.text.primary,
    letterSpacing: 0.3,
    marginTop: Spacing.xs,
  },
  leaderInset: {
    backgroundColor: Colors.bg.archive,
    borderRadius: Radius.md,
    padding: Spacing.md,
    marginTop: Spacing.xs,
    gap: Spacing.xs,
  },
  leaderLabel: {
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.xs,
    color: Colors.text.muted,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  leaderContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  leaderName: {
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.base,
    color: Colors.text.primary,
    flex: 1,
  },
  leaderPts: {
    fontFamily: FontFamily.displayBold,
    fontSize: FontSize.lg,
    color: Colors.accent.green,
  },
  progressBlock: {
    gap: Spacing.xs,
    marginTop: Spacing.xs,
  },
  progressTrack: {
    height: 4,
    borderRadius: 2,
    backgroundColor: Colors.bg.elevated,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 2,
    backgroundColor: Colors.accent.green,
  },
  progressLabel: {
    fontFamily: FontFamily.body,
    fontSize: FontSize.xs,
    color: Colors.text.muted,
    letterSpacing: 0.3,
  },
  noTournamentCard: {
    backgroundColor: Colors.bg.surface,
    borderRadius: Radius.xl,
    borderWidth: 1,
    borderColor: Colors.border.medium,
    borderStyle: 'dashed',
    padding: Spacing['2xl'],
    alignItems: 'center',
    gap: Spacing.md,
  },
  noTournamentPlus: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: Colors.accent.greenSubtle,
    borderWidth: 1,
    borderColor: Colors.accent.greenBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  noTournamentPlusText: {
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.xl,
    color: Colors.accent.green,
    lineHeight: 26,
  },
  noTournamentTitle: {
    fontFamily: FontFamily.displayBold,
    fontSize: FontSize.lg,
    color: Colors.text.secondary,
    letterSpacing: 0.8,
  },
  noTournamentDesc: {
    fontFamily: FontFamily.body,
    fontSize: FontSize.base,
    color: Colors.text.muted,
    textAlign: 'center',
    lineHeight: 20,
  },
  startTournamentBtn: {
    backgroundColor: Colors.accent.green,
    borderRadius: Radius.md,
    paddingHorizontal: Spacing.xl,
    paddingVertical: Spacing.md,
    marginTop: Spacing.xs,
  },
  startTournamentBtnText: {
    fontFamily: FontFamily.displayBold,
    fontSize: FontSize.md,
    color: Colors.accent.greenDark,
    letterSpacing: 0.8,
  },
  newMatchDayBtn: {
    backgroundColor: Colors.accent.green,
    borderRadius: Radius.lg,
    paddingVertical: Spacing.md,
    paddingHorizontal: Spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
  },
  newMatchDayBtnDisabled: {
    backgroundColor: Colors.bg.elevated,
    borderWidth: 1,
    borderColor: Colors.border.medium,
  },
  newMatchDayIcon: {
    width: 42,
    height: 42,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  newMatchDayIconActive: {
    backgroundColor: Colors.accent.greenDark,
  },
  newMatchDayIconDisabled: {
    backgroundColor: Colors.bg.elevated,
    borderWidth: 1,
    borderColor: Colors.border.medium,
  },
  newMatchDayIconText: {
    fontSize: FontSize.xl,
    lineHeight: 28,
  },
  newMatchDayIconTextActive: {
    color: Colors.accent.green,
    fontFamily: FontFamily.bodyBold,
  },
  newMatchDayIconTextDisabled: {
    color: Colors.text.muted,
    fontFamily: FontFamily.bodyBold,
  },
  newMatchDayTextBlock: {
    flex: 1,
    gap: 2,
  },
  newMatchDayBtnText: {
    fontFamily: FontFamily.display,
    fontSize: FontSize.lg,
    color: Colors.accent.greenDark,
    letterSpacing: 1,
  },
  newMatchDayBtnTextDisabled: {
    color: Colors.text.ghost,
  },
  newMatchDaySubtitle: {
    fontFamily: FontFamily.body,
    fontSize: FontSize.sm,
    color: Colors.text.muted,
  },
  quickRow: {
    flexDirection: 'row',
    gap: Spacing.md,
  },
  quickCard: {
    flex: 1,
    backgroundColor: Colors.bg.surface,
    borderRadius: Radius.xl,
    borderWidth: 1,
    borderColor: Colors.border.default,
    padding: Spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
  },
  quickIcon: {
    fontSize: 20,
  },
  quickCardTitle: {
    fontFamily: FontFamily.displayBold,
    fontSize: FontSize.md,
    color: Colors.text.primary,
    letterSpacing: 0.5,
  },
  quickCardSub: {
    fontFamily: FontFamily.body,
    fontSize: FontSize.xs,
    color: Colors.text.muted,
    marginTop: 2,
  },
});
