import { Colors } from '@/theme/colors';
import type { Player, Team, Match, ArchivedRound, ClosedTournament, KnownStatKey } from '@/store/types';

// ---------------------------------------------------------------------------
// Players & Teams
// ---------------------------------------------------------------------------
export const DEMO_PLAYERS: Player[] = [
  { id: 'demo-p1', name: 'Ruslan', nick: 'Rusik', teamCode: 'JUV' },
  { id: 'demo-p2', name: 'Artem', nick: 'Art', teamCode: 'TOT' },
  { id: 'demo-p3', name: 'Uz', teamCode: 'GAL' },
];

export const DEMO_TEAMS: Team[] = [
  { code: 'JUV', name: 'Juventus', short: 'JUV', color: Colors.team[0] },
  { code: 'TOT', name: 'Tottenham Hotspur', short: 'TOT', color: Colors.team[1] },
  { code: 'GAL', name: 'Galatasaray', short: 'GAL', color: Colors.team[2] },
];

// ---------------------------------------------------------------------------
// Per-match stats
//
// Every demo match gets a full statsOverride (all 23 keys) so that screens
// which aggregate real recorded stats — rather than match/[id]'s simulated
// display-only fallback (generateMatchStats) — have real data to show:
// Rivalry H2H Records/Comparison (src/utils/rivalryAggregation.ts) and
// Match-day Stats Records (src/utils/matchdayStatsAggregation.ts) both read
// match.statsOverride directly and render empty otherwise.
//
// Values follow each player's profile rather than the scoreline alone —
// Ruslan (JUV) is a direct attacker (shots/xG/shotAccuracy/central breaks),
// Artem (TOT) is a possession playmaker (passes/passAccuracy/tackles), Uz
// (GAL) is a winger/dribbler (wing breaks/successfulDribbles/corners) — so
// Rivalry's per-stat Best/Worst records read as distinct player identities
// instead of noise.
// ---------------------------------------------------------------------------
type StatRow = [number, number];

/** Builds a match's statsOverride from terse [a, b] tuples — keeps the 23-key rows below compact. */
function stats(input: Partial<Record<KnownStatKey, StatRow>>): NonNullable<Match['statsOverride']> {
  const out: NonNullable<Match['statsOverride']> = {};
  for (const [key, row] of Object.entries(input)) {
    if (!row) continue;
    out[key] = { a: row[0], b: row[1] };
  }
  return out;
}

// ---------------------------------------------------------------------------
// Champions Cup — closed tournament (Ruslan champion)
// ---------------------------------------------------------------------------
const CC_R1: Match[] = [
  {
    id: 'cc-r1-m1',
    aId: 'demo-p1',
    bId: 'demo-p2',
    aTeam: 'JUV',
    bTeam: 'TOT',
    aScore: 2,
    bScore: 0,
    statsOverride: stats({
      possession: [54, 46],
      timeToRegain: [4.5, 4.0],
      shots: [11, 3],
      expectedGoals: [2.6, 0.5],
      passes: [250, 330],
      tackles: [13, 15],
      successfulTackles: [8, 11],
      interceptions: [4, 7],
      saves: [0, 2],
      fouls: [6, 4],
      offsides: [2, 0],
      corners: [6, 2],
      freekicks: [3, 2],
      penaltyShots: [0, 0],
      yellowCards: [1, 0],
      redCards: [0, 0],
      breaksThroughCenter: [6, 1],
      breaksThroughWing: [2, 2],
      breaksThroughHigh: [3, 1],
      defBreakAttempts: [7, 9],
      successfulDribbles: [60, 38],
      shotAccuracy: [64, 33],
      passAccuracy: [72, 85],
    }),
  },
  {
    id: 'cc-r1-m2',
    aId: 'demo-p1',
    bId: 'demo-p3',
    aTeam: 'JUV',
    bTeam: 'GAL',
    aScore: 3,
    bScore: 1,
    statsOverride: stats({
      possession: [51, 49],
      timeToRegain: [4.6, 4.3],
      shots: [12, 6],
      expectedGoals: [2.9, 1.1],
      passes: [255, 270],
      tackles: [14, 11],
      successfulTackles: [9, 7],
      interceptions: [5, 4],
      saves: [1, 1],
      fouls: [7, 5],
      offsides: [3, 1],
      corners: [6, 5],
      freekicks: [3, 2],
      penaltyShots: [1, 0],
      yellowCards: [0, 0],
      redCards: [0, 0],
      breaksThroughCenter: [7, 2],
      breaksThroughWing: [2, 6],
      breaksThroughHigh: [3, 2],
      defBreakAttempts: [7, 6],
      successfulDribbles: [57, 68],
      shotAccuracy: [67, 50],
      passAccuracy: [73, 77],
    }),
  },
  {
    id: 'cc-r1-m3',
    aId: 'demo-p2',
    bId: 'demo-p3',
    aTeam: 'TOT',
    bTeam: 'GAL',
    aScore: 1,
    bScore: 2,
    statsOverride: stats({
      possession: [54, 46],
      timeToRegain: [3.9, 4.3],
      shots: [5, 8],
      expectedGoals: [0.9, 1.7],
      passes: [320, 260],
      tackles: [15, 11],
      successfulTackles: [11, 7],
      interceptions: [7, 4],
      saves: [2, 1],
      fouls: [4, 6],
      offsides: [0, 1],
      corners: [3, 6],
      freekicks: [2, 3],
      penaltyShots: [0, 0],
      yellowCards: [0, 0],
      redCards: [0, 0],
      breaksThroughCenter: [2, 2],
      breaksThroughWing: [2, 6],
      breaksThroughHigh: [1, 3],
      defBreakAttempts: [9, 6],
      successfulDribbles: [40, 72],
      shotAccuracy: [48, 56],
      passAccuracy: [86, 78],
    }),
  },
];

const CC_R2: Match[] = [
  {
    id: 'cc-r2-m1',
    aId: 'demo-p1',
    bId: 'demo-p2',
    aTeam: 'JUV',
    bTeam: 'TOT',
    aScore: 3,
    bScore: 2,
    statsOverride: stats({
      possession: [49, 51],
      timeToRegain: [4.7, 3.9],
      shots: [10, 7],
      expectedGoals: [2.5, 1.6],
      passes: [245, 345],
      tackles: [13, 16],
      successfulTackles: [8, 12],
      interceptions: [4, 8],
      saves: [1, 2],
      fouls: [6, 4],
      offsides: [1, 0],
      corners: [5, 4],
      freekicks: [3, 2],
      penaltyShots: [0, 0],
      yellowCards: [1, 0],
      redCards: [0, 0],
      breaksThroughCenter: [5, 2],
      breaksThroughWing: [2, 2],
      breaksThroughHigh: [2, 1],
      defBreakAttempts: [6, 9],
      successfulDribbles: [55, 44],
      shotAccuracy: [61, 52],
      passAccuracy: [71, 88],
    }),
  },
  {
    id: 'cc-r2-m2',
    aId: 'demo-p1',
    bId: 'demo-p3',
    aTeam: 'JUV',
    bTeam: 'GAL',
    aScore: 2,
    bScore: 1,
    statsOverride: stats({
      possession: [48, 52],
      timeToRegain: [4.5, 4.1],
      shots: [9, 7],
      expectedGoals: [2.1, 1.4],
      passes: [250, 285],
      tackles: [12, 12],
      successfulTackles: [8, 8],
      interceptions: [5, 5],
      saves: [1, 1],
      fouls: [5, 5],
      offsides: [2, 1],
      corners: [5, 7],
      freekicks: [2, 3],
      penaltyShots: [0, 0],
      yellowCards: [0, 1],
      redCards: [0, 0],
      breaksThroughCenter: [5, 2],
      breaksThroughWing: [2, 7],
      breaksThroughHigh: [3, 3],
      defBreakAttempts: [6, 6],
      successfulDribbles: [56, 70],
      shotAccuracy: [60, 55],
      passAccuracy: [74, 80],
    }),
  },
  {
    id: 'cc-r2-m3',
    aId: 'demo-p2',
    bId: 'demo-p3',
    aTeam: 'TOT',
    bTeam: 'GAL',
    aScore: 0,
    bScore: 1,
    statsOverride: stats({
      possession: [55, 45],
      timeToRegain: [4.0, 4.5],
      shots: [4, 6],
      expectedGoals: [0.6, 1.2],
      passes: [330, 250],
      tackles: [16, 10],
      successfulTackles: [12, 6],
      interceptions: [8, 4],
      saves: [3, 1],
      fouls: [4, 6],
      offsides: [0, 1],
      corners: [2, 5],
      freekicks: [2, 2],
      penaltyShots: [0, 0],
      yellowCards: [0, 0],
      redCards: [0, 0],
      breaksThroughCenter: [1, 2],
      breaksThroughWing: [1, 5],
      breaksThroughHigh: [1, 2],
      defBreakAttempts: [9, 5],
      successfulDribbles: [36, 60],
      shotAccuracy: [40, 52],
      passAccuracy: [88, 75],
    }),
  },
];

const CC_ARCHIVED_ROUNDS: ArchivedRound[] = [
  {
    id: 'cc-r1',
    n: 1,
    name: 'Round 1',
    date: '2026-03-15T14:00:00.000Z',
    winner: 'demo-p1',
    games: 3,
    ranked: true,
    matches: CC_R1,
  },
  {
    id: 'cc-r2',
    n: 2,
    name: 'Round 2',
    date: '2026-03-22T14:00:00.000Z',
    winner: 'demo-p1',
    games: 3,
    ranked: true,
    matches: CC_R2,
  },
];

const DEMO_CLOSED_TOURNAMENTS: ClosedTournament[] = [
  {
    id: 'demo-tour-cc',
    name: 'Champions Cup',
    date: '2026-03-23T16:00:00.000Z',
    rounds: CC_ARCHIVED_ROUNDS,
    champId: 'demo-p1',
    champName: 'Ruslan',
    champColor: Colors.team[0],
    champInit: 'RU',
    players: ['demo-p1', 'demo-p2', 'demo-p3'],
  },
];

// ---------------------------------------------------------------------------
// Premier League S2 — active tournament
// ---------------------------------------------------------------------------
// Round 1 — Ruslan wins (2W 6pts)
const PL_R1: Match[] = [
  {
    id: 'pl-r1-m1',
    aId: 'demo-p1',
    bId: 'demo-p2',
    aTeam: 'JUV',
    bTeam: 'TOT',
    aScore: 3,
    bScore: 1,
    statsOverride: stats({
      possession: [47, 53],
      timeToRegain: [4.8, 3.8],
      shots: [12, 5],
      expectedGoals: [2.8, 0.9],
      passes: [240, 350],
      tackles: [14, 17],
      successfulTackles: [9, 13],
      interceptions: [4, 9],
      saves: [1, 2],
      fouls: [7, 4],
      offsides: [2, 0],
      corners: [6, 3],
      freekicks: [4, 2],
      penaltyShots: [1, 0],
      yellowCards: [1, 0],
      redCards: [0, 0],
      breaksThroughCenter: [6, 1],
      breaksThroughWing: [2, 2],
      breaksThroughHigh: [3, 1],
      defBreakAttempts: [7, 10],
      successfulDribbles: [59, 40],
      shotAccuracy: [66, 45],
      passAccuracy: [70, 89],
    }),
  },
  {
    id: 'pl-r1-m2',
    aId: 'demo-p1',
    bId: 'demo-p3',
    aTeam: 'JUV',
    bTeam: 'GAL',
    aScore: 4,
    bScore: 2,
    statsOverride: stats({
      possession: [52, 48],
      timeToRegain: [4.4, 4.2],
      shots: [14, 8],
      expectedGoals: [3.3, 1.6],
      passes: [260, 275],
      tackles: [13, 11],
      successfulTackles: [9, 7],
      interceptions: [5, 4],
      saves: [1, 1],
      fouls: [6, 5],
      offsides: [3, 1],
      corners: [7, 6],
      freekicks: [3, 3],
      penaltyShots: [0, 0],
      yellowCards: [0, 0],
      redCards: [0, 0],
      breaksThroughCenter: [8, 2],
      breaksThroughWing: [2, 7],
      breaksThroughHigh: [4, 3],
      defBreakAttempts: [7, 6],
      successfulDribbles: [58, 73],
      shotAccuracy: [68, 53],
      passAccuracy: [73, 78],
    }),
  },
  {
    id: 'pl-r1-m3',
    aId: 'demo-p2',
    bId: 'demo-p3',
    aTeam: 'TOT',
    bTeam: 'GAL',
    aScore: 2,
    bScore: 0,
    statsOverride: stats({
      possession: [58, 42],
      timeToRegain: [3.7, 4.6],
      shots: [6, 3],
      expectedGoals: [1.4, 0.4],
      passes: [345, 235],
      tackles: [17, 10],
      successfulTackles: [13, 6],
      interceptions: [9, 4],
      saves: [3, 0],
      fouls: [3, 6],
      offsides: [0, 1],
      corners: [4, 3],
      freekicks: [2, 2],
      penaltyShots: [0, 0],
      yellowCards: [0, 1],
      redCards: [0, 0],
      breaksThroughCenter: [2, 1],
      breaksThroughWing: [2, 4],
      breaksThroughHigh: [1, 1],
      defBreakAttempts: [9, 5],
      successfulDribbles: [44, 55],
      shotAccuracy: [57, 38],
      passAccuracy: [88, 73],
    }),
  },
];

// Round 2 — Uz wins (2W 6pts)
const PL_R2: Match[] = [
  {
    id: 'pl-r2-m1',
    aId: 'demo-p1',
    bId: 'demo-p2',
    aTeam: 'JUV',
    bTeam: 'TOT',
    aScore: 2,
    bScore: 3,
    statsOverride: stats({
      possession: [45, 55],
      timeToRegain: [5.0, 3.7],
      shots: [9, 7],
      expectedGoals: [1.9, 1.9],
      passes: [235, 355],
      tackles: [12, 17],
      successfulTackles: [7, 13],
      interceptions: [3, 9],
      saves: [1, 3],
      fouls: [7, 3],
      offsides: [2, 0],
      corners: [5, 4],
      freekicks: [3, 2],
      penaltyShots: [0, 0],
      yellowCards: [1, 0],
      redCards: [0, 0],
      breaksThroughCenter: [5, 1],
      breaksThroughWing: [2, 2],
      breaksThroughHigh: [2, 1],
      defBreakAttempts: [6, 10],
      successfulDribbles: [52, 45],
      shotAccuracy: [55, 60],
      passAccuracy: [69, 90],
    }),
  },
  {
    id: 'pl-r2-m2',
    aId: 'demo-p1',
    bId: 'demo-p3',
    aTeam: 'JUV',
    bTeam: 'GAL',
    aScore: 1,
    bScore: 2,
    statsOverride: stats({
      possession: [44, 56],
      timeToRegain: [5.1, 4.0],
      shots: [7, 9],
      expectedGoals: [1.3, 2.0],
      passes: [230, 295],
      tackles: [11, 13],
      successfulTackles: [7, 9],
      interceptions: [4, 6],
      saves: [1, 1],
      fouls: [6, 5],
      offsides: [1, 1],
      corners: [4, 8],
      freekicks: [2, 3],
      penaltyShots: [0, 0],
      yellowCards: [0, 0],
      redCards: [0, 0],
      breaksThroughCenter: [4, 2],
      breaksThroughWing: [1, 8],
      breaksThroughHigh: [2, 3],
      defBreakAttempts: [5, 7],
      successfulDribbles: [50, 76],
      shotAccuracy: [48, 58],
      passAccuracy: [68, 81],
    }),
  },
  {
    id: 'pl-r2-m3',
    aId: 'demo-p2',
    bId: 'demo-p3',
    aTeam: 'TOT',
    bTeam: 'GAL',
    aScore: 0,
    bScore: 1,
    statsOverride: stats({
      possession: [53, 47],
      timeToRegain: [4.1, 4.4],
      shots: [4, 7],
      expectedGoals: [0.5, 1.5],
      passes: [315, 255],
      tackles: [15, 11],
      successfulTackles: [11, 7],
      interceptions: [7, 4],
      saves: [2, 1],
      fouls: [4, 6],
      offsides: [0, 1],
      corners: [2, 6],
      freekicks: [2, 3],
      penaltyShots: [0, 0],
      yellowCards: [0, 0],
      redCards: [0, 0],
      breaksThroughCenter: [1, 2],
      breaksThroughWing: [1, 6],
      breaksThroughHigh: [1, 3],
      defBreakAttempts: [8, 6],
      successfulDribbles: [41, 71],
      shotAccuracy: [38, 55],
      passAccuracy: [87, 76],
    }),
  },
];

const DEMO_ARCHIVED_ROUNDS: ArchivedRound[] = [
  {
    id: 'pl-r1',
    n: 1,
    name: 'Round 1',
    date: '2026-04-12T14:00:00.000Z',
    winner: 'demo-p1',
    games: 3,
    ranked: true,
    matches: PL_R1,
  },
  {
    id: 'pl-r2',
    n: 2,
    name: 'Round 2',
    date: '2026-04-19T14:00:00.000Z',
    winner: 'demo-p3',
    games: 3,
    ranked: true,
    matches: PL_R2,
  },
];

// Round 3 — currently open (2 of 3 matches played)
const DEMO_CURRENT_MATCHES: Match[] = [
  {
    id: 'pl-r3-m1',
    aId: 'demo-p1',
    bId: 'demo-p2',
    aTeam: 'JUV',
    bTeam: 'TOT',
    aScore: 2,
    bScore: 1,
    statsOverride: stats({
      possession: [48, 52],
      timeToRegain: [4.6, 3.9],
      shots: [10, 6],
      expectedGoals: [2.3, 1.1],
      passes: [250, 340],
      tackles: [13, 16],
      successfulTackles: [8, 12],
      interceptions: [4, 8],
      saves: [1, 2],
      fouls: [6, 4],
      offsides: [2, 0],
      corners: [6, 3],
      freekicks: [3, 2],
      penaltyShots: [0, 0],
      yellowCards: [0, 0],
      redCards: [0, 0],
      breaksThroughCenter: [6, 1],
      breaksThroughWing: [2, 2],
      breaksThroughHigh: [3, 1],
      defBreakAttempts: [7, 9],
      successfulDribbles: [57, 42],
      shotAccuracy: [63, 48],
      passAccuracy: [72, 87],
    }),
  },
  {
    id: 'pl-r3-m2',
    aId: 'demo-p2',
    bId: 'demo-p3',
    aTeam: 'TOT',
    bTeam: 'GAL',
    aScore: 1,
    bScore: 1,
    statsOverride: stats({
      possession: [51, 49],
      timeToRegain: [4.0, 4.3],
      shots: [5, 6],
      expectedGoals: [1.0, 1.1],
      passes: [300, 280],
      tackles: [14, 12],
      successfulTackles: [10, 8],
      interceptions: [6, 5],
      saves: [2, 1],
      fouls: [5, 5],
      offsides: [0, 1],
      corners: [3, 5],
      freekicks: [2, 3],
      penaltyShots: [0, 0],
      yellowCards: [0, 0],
      redCards: [0, 0],
      breaksThroughCenter: [2, 3],
      breaksThroughWing: [2, 6],
      breaksThroughHigh: [1, 2],
      defBreakAttempts: [7, 6],
      successfulDribbles: [43, 66],
      shotAccuracy: [50, 52],
      passAccuracy: [80, 77],
    }),
  },
];

// ---------------------------------------------------------------------------
// Full demo state snapshot (injected into the store)
// ---------------------------------------------------------------------------
export const DEMO_STATE = {
  tournamentId: 'demo-tour-pl-s2',
  players: DEMO_PLAYERS,
  teams: DEMO_TEAMS,

  hasTournament: true,
  tournamentName: 'Premier League S2',
  round: 3,
  roundOpen: true,
  tournamentRanked: true,
  tournamentPlayers: ['demo-p1', 'demo-p2', 'demo-p3'] as string[],
  roundPlayers: ['demo-p1', 'demo-p2', 'demo-p3'] as string[],
  matches: DEMO_CURRENT_MATCHES,
  archivedRounds: DEMO_ARCHIVED_ROUNDS,
  closedTournaments: DEMO_CLOSED_TOURNAMENTS,

  showNick: true,
  showTeamLogo: true,
  language: 'en',
} as const;
